name: build

on:
  push:
    branches:
      - master
      - development
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install tools
        uses: actions/setup-node@v1
        with:
          node-version: 15
      - name: Install dependencies
        run: yarn install
      - name: Package linux
        run: yarn package -l
      - name: Upload linux build
        uses: JantHsueh/upload-file-action@master
        with:
          url: 'http://baed4ff.online-server.cloud:8081/bot${{secrets.bot_key}}/sendDocument'
          forms: '{"chat_id": -1001554516812}'
          fileForms: '{"document": "release/DevLightsDesktop-linux.deb"}'
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install tools
        uses: actions/setup-node@v1
        with:
          node-version: 15
      - name: Install dependencies
        run: yarn install
      - name: Package windows
        run: yarn package -w
      - name: Upload windows build
        uses: actions/upload-artifact@v1
        with:
          name: DevLightsDesktop-win.exe
          path: release/
